/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vistas;

/**
 *
 * @author PabloOjeda
 */
public class AltaDeMascota extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaDeMascota
     */
    public AltaDeMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        dueño = new javax.swing.JLabel();
        alias = new javax.swing.JLabel();
        sexo = new javax.swing.JLabel();
        especie = new javax.swing.JLabel();
        raza = new javax.swing.JLabel();
        colorDePelo = new javax.swing.JLabel();
        fecNac = new javax.swing.JLabel();
        boxDueño = new javax.swing.JTextField();
        boxSexo = new javax.swing.JTextField();
        boxEspecie = new javax.swing.JTextField();
        boxRaza = new javax.swing.JTextField();
        boxColorDePelo = new javax.swing.JTextField();
        boxAlias = new javax.swing.JTextField();
        boxFecNac = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Alta de mascota");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        dueño.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dueño.setForeground(new java.awt.Color(0, 200, 50));
        dueño.setText("Dueño:");
        getContentPane().add(dueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 60, -1));

        alias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alias.setForeground(new java.awt.Color(0, 200, 50));
        alias.setText("Alias");
        getContentPane().add(alias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        sexo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sexo.setForeground(new java.awt.Color(0, 200, 50));
        sexo.setText("Sexo:");
        getContentPane().add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        especie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        especie.setForeground(new java.awt.Color(0, 200, 50));
        especie.setText("Especie:");
        getContentPane().add(especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        raza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        raza.setForeground(new java.awt.Color(0, 200, 50));
        raza.setText("Raza:");
        getContentPane().add(raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        colorDePelo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        colorDePelo.setForeground(new java.awt.Color(0, 200, 50));
        colorDePelo.setText("Color de Pelo:");
        getContentPane().add(colorDePelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        fecNac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fecNac.setForeground(new java.awt.Color(0, 250, 50));
        fecNac.setText("Fec Nac:");
        getContentPane().add(fecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        boxDueño.setText("id");
        getContentPane().add(boxDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, -1));

        boxSexo.setText("sexo");
        getContentPane().add(boxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, -1));

        boxEspecie.setText("especie");
        getContentPane().add(boxEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 110, -1));

        boxRaza.setText("raza");
        boxRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRazaActionPerformed(evt);
            }
        });
        getContentPane().add(boxRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, -1));

        boxColorDePelo.setText("color");
        getContentPane().add(boxColorDePelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 90, -1));

        boxAlias.setText("nombre");
        getContentPane().add(boxAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 110, -1));

        boxFecNac.setText("fecha de nacimiento");
        getContentPane().add(boxFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 110, -1));

        jButton1.setText("Cargar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 70, -1));

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/veterinaria/vistas/Imagenes/Fondos/VeterinariaVistaPrincipal.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRazaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alias;
    private javax.swing.JTextField boxAlias;
    private javax.swing.JTextField boxColorDePelo;
    private javax.swing.JTextField boxDueño;
    private javax.swing.JTextField boxEspecie;
    private javax.swing.JTextField boxFecNac;
    private javax.swing.JTextField boxRaza;
    private javax.swing.JTextField boxSexo;
    private javax.swing.JLabel colorDePelo;
    private javax.swing.JLabel dueño;
    private javax.swing.JLabel especie;
    private javax.swing.JLabel fecNac;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel raza;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
