/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vistas;
    
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import veterinaria.modelo.Conexion;
import veterinaria.modelo.Mascota;
import veterinaria.modelo.Visita;
import veterinaria.modelo.VisitaData;

/**
 *
 * @author nachomorati
 */
public class VistaHistorialVisitas extends javax.swing.JInternalFrame {
    private DefaultTableModel modelo;
    private Conexion conexion;
    private Mascota mascota;
    private VisitaData visitaData;
    private ArrayList<Visita> visitas;

    /**
     * Creates new form VistaHistorialVisitas
     */
    public VistaHistorialVisitas(Mascota mascota) {
        initComponents();
        
        try {
            this.mascota = mascota;
            modelo = new DefaultTableModel();
            conexion = new Conexion("jdbc:mysql://localhost/veterinaria", "root", "");
            visitaData = new VisitaData(conexion);
            visitas = (ArrayList)visitaData.obtenerVisitas();
            
            labelAlias.setText("Visitas de " + mascota.getAlias());
        
            armarCabecera();
            cargaDatos();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaHistorialVisitas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    public Mascota getMascota() {
        return mascota;
    }
    
    

    public void setMascota(Mascota mascota) {
        this.mascota = mascota;
    }
    
    public void armarCabecera() {
        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("Fecha");
        columnas.add("Veterinario");
        columnas.add("Peso");
        columnas.add("Tratamiento");
        columnas.add("Detalles");
        for(Object item:columnas) {
            modelo.addColumn(item);
        }
        jtableVisitas.setModel(modelo);
    }
    
    public void cargaDatos(){
        for (Visita visita:visitas) {
            if(visita.getMascota().getId() == mascota.getId()) {
                modelo.addRow(new Object[]{visita.getFecha(), visita.getVeterinario(), visita.getPesoActual(), visita.getTratamiento().getDescripcion(), visita.getDetalles()});
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAlias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableVisitas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        labelAlias.setText("Visitas");

        jtableVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtableVisitas);

        jButton1.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(labelAlias)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAlias)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableVisitas;
    private javax.swing.JLabel labelAlias;
    // End of variables declaration//GEN-END:variables
}
